
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nook-weather
spec:
  replicas: 1
  selector:
    matchLabels:
     app: nook-weather
  template:
    metadata:
      labels:
        app: nook-weather
    spec:
      containers:
      - name: nook-weather
        image: thecase/nook-weather:1.0
        env:
        - name: BIND_PORT
          value: "8080"
        - name: DARKSKY_API_KEY
          valueFrom:
            secretKeyRef:
              name: darksky
              key: api_key
        - name: GPS_COORDINATES
          valueFrom:
            secretKeyRef:
              name: darksky
              key: gps_coordinates
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nook-weather
  labels:
    component: nook-weather
spec:
  type: LoadBalancer
  selector:
    app: nook-weather
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: nook-weather-ingress
#  annotations:
#    kubernetes.io/ingress.class: traefik
#spec:
#  rules:
#  - host: nook-weather.svc
#    http:
#      paths:
##      - path: /
#      - backend:
#          serviceName: nook-weather
#          servicePort: 8080
